name: SnapShareEvent
options:
  bundleIdPrefix: com.snapshare
  deploymentTarget:
    iOS: 16.0
  developmentLanguage: ja
  xcodeVersion: 15.0

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.20.0
  SDWebImageSwiftUI:
    url: https://github.com/SDWebImage/SDWebImageSwiftUI
    from: 2.2.6
  Cloudinary:
    url: https://github.com/cloudinary/cloudinary_ios
    from: 4.0.0

targets:
  SnapShareEvent:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    sources:
      - path: .
        excludes:
          - "*.md"
          - "*.yml"
          - "*.template"
          - ".git"
          - ".gitignore"
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.snapshare.event
        TARGETED_DEVICE_FAMILY: 1
        SWIFT_VERSION: 5.9
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: SDWebImageSwiftUI
      - package: Cloudinary
        product: Cloudinary
    info:
      path: Info.plist
      properties:
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiresFullScreen: true
        UIStatusBarStyle: UIStatusBarStyleDefault
        NSCameraUsageDescription: "イベントの写真を撮影して友達と共有するためにカメラへのアクセスが必要です"
        NSPhotoLibraryUsageDescription: "写真を保存するためにフォトライブラリへのアクセスが必要です"
        NSPhotoLibraryAddUsageDescription: "撮影した写真をフォトライブラリに保存するためのアクセスが必要です"
